moonraker:
  url: "http://localhost:7125"

proxy:
  host: "0.0.0.0"
  port: 7126
  debug: false  # Set to true for detailed logging

preprocessing_rules:
  - name: "example_rule"
    script: "scripts/example_rule.py"
    enabled: true
